# Info
title: Bob Pony

# Compression config
compress_html:
    comments: all

# Excludes non-related files
exclude:
  - CNAME
  - .gitignore
  - LICENSE
  - README.md

# Plugins for Jekyll
plugins:
  - jekyll-sitemap
